### ISSUE TITLE
Prisma Client 버전에 문제가 있는 것 같습니다

### ISSUE THREAD

**Issue by idleJinseok** [teslamint/chzzk-songrequest#167]
제가 제대로 한게 맞다면, Prisma Client 버전이 안 맞아서 컨테이너가 실행이 안 됩니다.

아래는 출력된 오류입니다.

app-1    | Environment variables loaded from .env
app-1    | Prisma schema loaded from prisma/schema.prisma
app-1    |
app-1    | ✔ Generated Prisma Client (v5.18.0) to ./node_modules/.pnpm/@prisma+client@5.18.0_prisma@5.16.1/node_modules/@prisma/client in 57ms
app-1    |
app-1    | Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
app-1    | ```
app-1    | import { PrismaClient } from '@prisma/client'
app-1    | const prisma = new PrismaClient()
app-1    | ```
app-1    | or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
app-1    | ```
app-1    | import { PrismaClient } from '@prisma/client/edge'
app-1    | const prisma = new PrismaClient()
app-1    | ```
app-1    |
app-1    | See other ways of importing Prisma Client: http://pris.ly/d/importing-client
app-1    |
app-1    | ┌─────────────────────────────────────────────────────────────┐
app-1    | │  Deploying your app to serverless or edge functions?        │
app-1    | │  Try Prisma Accelerate for connection pooling and caching.  │
app-1    | │  https://pris.ly/cli/--accelerate                           │
app-1    | └─────────────────────────────────────────────────────────────┘
app-1    |
app-1    |
app-1    | warn Versions of prisma@5.16.1 and @prisma/client@5.18.0 don't match.
app-1    | This might lead to unexpected behavior.
app-1    | Please make sure they have the same version.
app-1    | Environment variables loaded from .env
app-1    | Prisma schema loaded from prisma/schema.prisma
app-1    | Datasource "db": PostgreSQL database
app-1    |
app-1    | Error: Prisma schema validation - (get-config wasm)
app-1    | Error code: P1012
app-1    | error: Environment variable not found: DATABASE_URL.
app-1    |   -->  prisma/schema.prisma:13
app-1    |    |
app-1    | 12 |   provider = "postgresql"
app-1    | 13 |   url      = env("DATABASE_URL")
app-1    |    |
app-1    |
app-1    | Validation Error Count: 1
app-1    | [Context: getConfig]
app-1    |
app-1    | Prisma CLI Version : 5.16.1
app-1 exited with code 1

해결 방법이 있을까요?

**Comment by teslamint** [comment]
dependabot이 `@prisma/client` 버전을 올렸는데 정작 `prisma` 패키지 버전은 안 올렸네요.
#172 에서 수정했습니다.
